const text = [
  `It was a bright and sunny morning. The sky was clear, and the birds were singing. Emily woke up early, feeling excited. It was Saturday, and she had planned to go to the park with her little brother, Ben.
After breakfast, Emily packed a small bag. She took sandwiches, juice boxes, a frisbee, and a blanket. Ben grabbed his toy truck and followed her to the door. Their mom smiled and reminded them to be careful and stay together.
The park was only a short walk from their house. On the way, they saw a black cat sitting on a fence. It blinked slowly as they passed. Emily and Ben waved at it, even though the cat didn't wave back.
When they reached the park, they found a quiet spot under a big oak tree. Emily laid out the blanket and gave Ben his juice. He sat down happily and started playing with his truck in the grass. Emily took out her book and read a few pages, but soon Ben asked her to play.
They ran around in the open field, tossing the frisbee back and forth. Sometimes Ben missed, and the frisbee landed in a bush. Emily helped him get it out each time. They laughed a lot and didn't even notice how fast time was flying.
After playing, they sat down to eat. The sandwiches were simple, just peanut butter and jelly, but they tasted great in the fresh air. They shared a chocolate bar for dessert and drank their juice.
A dog came by and wagged its tail. It looked friendly, so Emily let it sniff her hand. Ben giggled when the dog licked his face. The owner came running and said thank you before calling the dog back. Emily waved and smiled.
Later, they went to the small playground nearby. Ben climbed up the ladder and slid down the slide again and again. Emily pushed him gently on the swing. He shouted with joy each time he flew up into the air.
As the sun began to set, the sky turned orange and pink. Emily packed up their things, and they walked home slowly. Ben was tired and held her hand the whole way. When they reached home, their mom was waiting at the door.
“Did you have fun?” she asked.
“Yes!” Ben said, smiling. “We played, ate, and saw a dog!”
Emily nodded. “It was a perfect day."
They washed up, had dinner, and went to bed early. As Emily closed her eyes, she thought about the sun, the grass, and Ben's happy face. She smiled and fell asleep.`,

  `The sun rose slowly over the quiet village, spilling golden light across the thatched rooftops and cobblestone streets. Birds sang as they flitted between the branches of ancient trees, their melodies blending with the soft murmur of a nearby stream. Villagers began their daily routines, some tending to gardens heavy with dew, others leading animals to pasture. The aroma of freshly baked bread drifted from open windows, mingling with the scent of damp earth and wildflowers. Children laughed as they chased one another across open fields, their footsteps soft against the grass. Somewhere, a blacksmith struck iron with rhythmic precision, the sound echoing through the narrow alleys. Time seemed slower here, measured not in schedules or deadlines, but in the rising and setting of the sun, the passage of seasons, and the quiet rituals of everyday life. Even the wind appeared to move more deliberately, carrying stories of distant lands while rustling the leaves above. In such a place, one could pause and breathe deeply, aware of the connection between all living things, and find serenity in the harmony of nature and community, a reminder that life's richness often exists in the simplest moments.`,
  `The city woke with a buzz of energy, skyscrapers catching the first light of dawn and reflecting it in dazzling patterns across glass facades. Traffic moved steadily, cars honking intermittently as they navigated crowded avenues, while pedestrians hurried along sidewalks with the determination of people chasing purpose and deadlines. Cafes opened, filling the air with the scent of coffee and baked pastries, attracting workers seeking a quick start to the day. Street performers began their routines, drawing small crowds who paused to watch skilled musicians, dancers, and artists bring the concrete environment to life. Neon signs flickered in preparation for the coming day, announcing everything from freshly pressed suits to exotic delicacies. Amidst this constant motion, moments of stillness emerged—a mother tying her child's shoes, a man pausing to read a sign, pigeons settling briefly on ledges above. The city, a living organism, breathed in cycles of chaos and calm, movement and pause. It thrived on diversity, each person contributing to the intricate web of existence. Even in the loudest streets, one could find a rhythm, a balance between ambition and reflection, chaos and beauty, forming a cityscape alive with human stories.`,
  `The library was silent except for the occasional turning of a page or the soft footsteps of a visitor moving through the aisles. Towering shelves, filled with books of every imaginable subject, rose toward the high ceiling, their spines a mosaic of colors and textures. The scent of aged paper and polished wood filled the air, creating an atmosphere of quiet reverence. Students bent over desks, scribbling notes or typing on laptops, immersed in the pursuit of knowledge, while others wandered slowly, searching for inspiration or discovery. Sunlight filtered through tall windows, casting geometric patterns on the marble floor and illuminating motes of dust that drifted lazily in the beams. In one corner, a reader traced lines of poetry with a fingertip, savoring the rhythm and cadence, while across the room, a scholar consulted multiple references for an essay due the next day. Every book held a story, every page a fragment of someone's imagination or research. The library was a sanctuary where the mind could wander, explore, and expand, a place that connected generations of thinkers and dreamers through time, reminding all who entered that knowledge is a bridge across ages and ideas, endlessly inviting curiosity and reflection.`,
  `Beneath the endless sky, the desert stretched in waves of golden sand, each dune shaped by winds that had blown for centuries. The heat of the day was relentless, but the wind brought a dry, whispering coolness that shifted with the contours of the terrain. In the distance, the silhouette of a solitary traveler appeared, moving slowly but steadily, leaving a trail that would soon be erased by the desert's natural rhythm. Small desert creatures emerged cautiously, adapted to the harsh environment, seeking shelter or sustenance in the sparse vegetation that clung to the sand. The silence was profound, broken only by the occasional gust that lifted sand in spiraling patterns, creating shifting mosaics of shadow and light. At night, the moon rose, casting silver light across the dunes, and stars appeared in unimaginable numbers, illuminating the landscape with quiet brilliance. In this vast emptiness, one could feel both insignificance and connection, a reminder of the scale of the universe and the resilience required to exist within it. The desert, harsh yet mesmerizing, demanded respect and patience, offering a unique beauty that revealed itself only to those willing to observe carefully and endure its challenges.`,
  `The marketplace teemed with life, a vibrant mosaic of colors, sounds, and scents that assaulted the senses in the most exhilarating way. Merchants displayed an array of goods, from fragrant spices and ripe fruits to finely woven fabrics and handcrafted ornaments. Customers haggled animatedly, exchanging coins for items, voices rising in rhythm with the bustling energy surrounding them. Children ran between stalls, laughter ringing out as vendors shouted greetings or warnings in quick succession. Aromas of sizzling food from small street stalls mingled with the fragrance of fresh flowers, creating a complex sensory tapestry. Sunlight filtered through hanging tarps and awnings, casting shifting shadows across the cobblestones, while pigeons occasionally swooped in, adding motion to the lively scene. Each individual contributed to the ever-changing rhythm of the marketplace, their actions weaving together into an intricate story of commerce, culture, and daily survival. In such a setting, life's diversity was on full display, a reminder that even the busiest, most chaotic environments carried patterns, stories, and connections waiting to be discovered by those who paused long enough to notice.`,
];

export default text;
